# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99aad9ce580c25f5fdfa89a227690262c25c2ef0ab323cdb2109da374a12e34bd07d0028e47a992c81ea67c608a5f32c7fb43a1cae59a67cc8bed0f8daff9972

test:
  secret_key_base: bcfcd5798eb6ebfddbebcc00bc89627ca871b953771575c9dd30d8657463c59ede6381d5534de5a9b7ed2f85aaa43ad1a1e8b34c1187f8e0696e6daaf15b6b37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
